name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Get tooling
      run: |
        go get golang.org/x/lint/golint
        go get honnef.co/go/tools/cmd/staticcheck

    - name: Build
      run: go build -v -tags=gofuzz ./...

    - name: vet
      run: go vet ./...

    - name: staticcheck
      run: staticcheck ./...

    - name: lint
      run: golint -set_exit_status ./cmd/... ./internal/...

    - name: Test
      run: go test -v -race ./...